# Generated by Django 4.2.2 on 2023-06-24 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Duvacki_Instrumenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Trumpets_Type', models.CharField(max_length=200)),
                ('Trumpets_Bore_Size', models.CharField(max_length=200)),
                ('Trumpets_Bell', models.CharField(max_length=200)),
                ('Trumpets_Valve', models.CharField(blank=True, max_length=200, null=True)),
                ('Trumpets_Leadpipe', models.CharField(blank=True, max_length=200, null=True)),
                ('Trumpets_Finish', models.CharField(blank=True, max_length=200, null=True)),
                ('Trumpets_Options', models.CharField(blank=True, max_length=200, null=True)),
                ('Video', models.CharField(blank=True, max_length=2000, null=True)),
                ('Photos', models.ImageField(blank=True, null=True, upload_to='')),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Slobodni_Aerofoni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=200)),
                ('Model', models.CharField(max_length=200)),
                ('Type', models.CharField(max_length=200)),
                ('Reeds', models.CharField(max_length=200)),
                ('Bass', models.CharField(max_length=200)),
                ('Weight', models.CharField(max_length=200)),
                ('Features', models.CharField(max_length=200)),
                ('Includes', models.CharField(max_length=200)),
                ('Suggested_Upgrades', models.CharField(max_length=200)),
                ('Price', models.IntegerField()),
                ('Video', models.CharField(max_length=2000)),
                ('Photos', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Prodavac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Surname', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Transaction_account', models.IntegerField()),
                ('Password', models.CharField(max_length=200)),
                ('Confirm_password', models.CharField(max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kupuvac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Surname', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('Mobile_Number', models.IntegerField()),
                ('Card', models.IntegerField()),
                ('CVV', models.IntegerField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
